import type { Metadata } from 'next';
import '@/styles/globals.css';
import Header from '@/components/header';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'beer-next',
  description: 'Generated by create next app',
};

const font = localFont({
  src: './fonts/PretendardVariable.ttf',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={font.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
