import type { Metadata } from 'next';
import '@/styles/globals.css';
import Header from '@/components/header';

export const metadata: Metadata = {
  title: 'beer-next',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
