import Header from '@/components/header';
import '@/styles/globals.css';
import profile from '@public/profile.png';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'beer-next',
  description: 'Generated by create next app',
};

const font = localFont({
  src: '../fonts/PretendardVariable.ttf',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={font.className}>
      <body>
        <Header />
        <Image src={profile} alt="profile image" width={300} height={300} />
        {children}
      </body>
    </html>
  );
}
