import Header from '@/components/header';
import Profile from '@/components/profile';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'beer-next',
  description: 'Generated by create next app',
};

const font = localFont({
  src: '../fonts/PretendardVariable.ttf',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={font.className}>
      <body className="min-h-screen">
        <Header />
        <div className=" flex justify-around m-4 py-10">
          <div className="flex-[0.3] flex justify-center items-start">
            <Profile />
          </div>
          <main className="flex-[0.7] flex justify-center items-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
